Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 512
    end
    config.vm.provision "shell", path: "setup_install_docker.sh"
    config.vm.provision "shell", path: "setup_nodejs.sh"
    config.vm.synced_folder "../../", "/home/vagrant/databases"

    config.vm.define "list_postgres" do |list_postgres|
        list_postgres.vm.network "private_network", ip: "192.168.60.2"
        list_postgres.vm.provision "shell", path: "setup_run_database.sh", args: "postgres"
    end
end
