name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "src/**"

jobs:

  publish:
    name: publish @next to npm
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    with:
      semver-bump: prerelease
