name: Verify

on:
  push:
    branches: [ main ]
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - typecheck
    steps:
      - run: echo "Dorcas Reilly's Green Beans"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i -P
      - run: pnpm build
      - run: pnpm dev -h

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install virtualbox
        run: |
          sudo apt-get -qq update && sudo apt-get -qq -y install virtualbox
      - name: install vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get -qq update && sudo apt-get -qq -y install vagrant
      - name: install pnpm
        run: |
          corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm build
      - run: vagrant up
        working-directory: test/vms
      - run: pnpm test

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm check
